CREATE DATABASE IF NOT EXISTS kr3db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kr3db;

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kr3_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title_mon VARCHAR(500) NOT NULL,
  title_eng VARCHAR(500),
  verbatim TEXT,
  explanation LONGTEXT,
  video_url VARCHAR(500),
  image_url VARCHAR(500),
  email_image_url VARCHAR(500),
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kr3_tables (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  title VARCHAR(500),
  rows_data JSON NOT NULL,
  sort_order INT DEFAULT 0,
  FOREIGN KEY (item_id) REFERENCES kr3_items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kr3_evidence (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  label VARCHAR(500),
  file_path VARCHAR(500),
  sort_order INT DEFAULT 0,
  FOREIGN KEY (item_id) REFERENCES kr3_items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
